From microsoft/dotnet:2.1-sdk AS build
WORKDIR /app

COPY PLCBus/PLCBus.csproj ./PLCBus/
COPY Messages/Messages.csproj ./Messages/

WORKDIR /app/PLCBus
RUN dotnet restore

WORKDIR /app
COPY PLCBus/. ./PLCBus/
COPY Messages/. ./Messages/

WORKDIR /app/PLCBus
RUN dotnet publish  -c Release -o out

#tests
#FROM build as testrunner
#WORKDIR /app/tests
#COPY tests/. .
#ENTRYPOINT ["dotnet", "test","--logger:trx"]

FROM microsoft/dotnet:2.1.4-aspnetcore-runtime AS runtime
WORKDIR /app
COPY --from=build /app/PLCBus/out ./


ENTRYPOINT ["dotnet", "PLCBus.dll"]
