FROM python:3

RUN pip install stompest pyownet apscheduler futures  pbr funcsigs pika virtualenv

RUN apt-get update

RUN apt-get install --force-yes -y make libudev-dev g++ libyaml-dev

RUN pip install python_openzwave
#RUN source venv3/bin/activate

#CMD ["pyozw_check", "-i","-d", "/dev/zwave"]

COPY ZWave_Python/ZWave_Python.py ./
COPY ZWave_Python/config.json ./

CMD ["python", "ZWave_Python.py"]
